before:
  hooks:
    - go mod download
builds:
  - goos:
      - linux
      - windows
      - darwin
    main: ./hello.go
    ldflags:
      - -X main.Version={{.Env.CIRCLE_TAG}}
brews:
  - name: "{{ .Env.CIRCLE_PROJECT_REPONAME }}"
    tap:
      owner: bmbferreira
      name: "{{ .Env.CIRCLE_PROJECT_REPONAME }}"
archives:
  - name_template: "{{ .Env.CIRCLE_PROJECT_REPONAME }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
