# This file was generated by GoReleaser. DO NOT EDIT.
class GolangCliExample < Formula
  desc ""
  homepage ""
  version "0.0.10-alpha.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bmbferreira/golang-cli-example/releases/download/v0.0.10-alpha.10/golang-cli-example-0.0.10-alpha.10-darwin-amd64.tar.gz", :using => GitDownloadStrategy
    sha256 "c8268866f89d19b26c2309510f1cde7bad5e0f34909b6021cd10e0a3c4d1cd66"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bmbferreira/golang-cli-example/releases/download/v0.0.10-alpha.10/golang-cli-example-0.0.10-alpha.10-linux-amd64.tar.gz", :using => GitDownloadStrategy
      sha256 "bb1ba3e811254fd7db55554bee09bd65b4775e73561e7d6b5b01dd5a85292a45"
    end
  end

  def install
    bin.install "golang-cli-example"
  end
end
