# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "private"
class GolangCliExample < Formula
  desc ""
  homepage ""
  version "0.0.11-alpha.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bmbferreira/golang-cli-example/releases/download/v0.0.11-alpha.11/golang-cli-example-0.0.11-alpha.11-darwin-amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "596bdeb19ecf47305282d4396d985ef68f2eb04c70da5df6390219b2ac80afd5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bmbferreira/golang-cli-example/releases/download/v0.0.11-alpha.11/golang-cli-example-0.0.11-alpha.11-linux-amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c098862897fa7cae078718c8e26643330a5f29d4784b6d399b4aa8c89533da09"
    end
  end

  def install
    bin.install "golang-cli-example"
  end
end
