version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/golang-cli-example
    steps:
      - checkout
      - run:
          name: Building
          # TODO: other archs/oses
          command: |
            VERSION=${CIRCLE_TAG}
            GOOS=linux GOARCH=amd64 go build -ldflags "-X main.Version=${VERSION}" -o bin/hello-${VERSION}-linux-amd64 hello.go
            GOOS=linux GOARCH=386 go build -ldflags "-X main.Version=${VERSION}" -o bin/hello-${VERSION}-linux-386 hello.go
            GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.Version=${VERSION}" -o bin/hello-${VERSION}-darwin-amd64 hello.go
            GOOS=darwin GOARCH=386 go build -ldflags "-X main.Version=${VERSION}" -o bin/hello-${VERSION}-darwin-386 hello.go
            GOOS=windows GOARCH=amd64 go build -ldflags "-X main.Version=${VERSION}" -o bin/hello-${VERSION}-windows-amd64.exe hello.go
            GOOS=windows GOARCH=386 go build -ldflags "-X main.Version=${VERSION}" -o bin/hello-${VERSION}-windows-386.exe hello.go
      - persist_to_workspace:
          root: .
          paths:
            - bin
  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ~/golang-cli-example
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/golang-cli-example/bin
workflows:
  version: 2
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*/
