version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/golang-cli-example
    steps:
      - checkout
      - run:
          name: Building
          command: |
            curl -sL https://git.io/goreleaser | CIRCLE_TAG=snapshot bash -s build --snapshot --rm-dist
  release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Releasing
          command: |
            curl -sL https://git.io/goreleaser | bash -s release --rm-dist
workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*/
