# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class GolangCliExample < Formula
  desc ""
  homepage ""
  version "0.0.17-alpha.17"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bmbferreira/golang-cli-example/releases/download/v0.0.17-alpha.17/golang-cli-example-0.0.17-alpha.17-darwin-amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "e79bf7528773d013ff0dfca215a82f10e88f64c5629234442dbf1db58e4207a6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bmbferreira/golang-cli-example/releases/download/v0.0.17-alpha.17/golang-cli-example-0.0.17-alpha.17-linux-amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8b247e913f120fbcaaa385b7afbe2f6d9fbde021117de51f4012246ef56351e4"
    end
  end

  def install
    bin.install "golang-cli-example"
  end
end
