# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class GolangCliExample < Formula
  desc ""
  homepage ""
  version "0.0.20-alpha.20"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bmbferreira/golang-cli-example/releases/download/v0.0.20-alpha.20/golang-cli-example-0.0.20-alpha.20-darwin-amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "b12ab5998e6e1d6f7ceba982a6619e8533632d8a899f82ef77062ca4b95ef724"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bmbferreira/golang-cli-example/releases/download/v0.0.20-alpha.20/golang-cli-example-0.0.20-alpha.20-linux-amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "abbc6e23e9f3cac4aa079c43c1b5b8863088249d25bd5277f6b713435dfb6773"
    end
  end

  def install
    bin.install "golang-cli-example"
  end
end
